#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Sep 26 19:50:10 2022

@author: student
"""

import pygame
from pygame.draw import *

pygame.init()

FPS = 30
screen = pygame.display.set_mode((794, 1123))
 
color=(230, 230, 230)

rect(screen, (0, 255, 255), (0, 0, 794, 523))

rect(screen, color, (0, 523, 794, 600))
line(screen, (0, 0, 0), (0, 523), (794, 523), 1)

circle(screen, (161, 249, 228), (470, 200), 280, 25)

ellipse(screen, color, (130, 430, 170, 510))
ellipse(screen, (0, 0, 0), (130, 430, 170, 510), 1)

ellipse(screen, color, (3, 490, 250, 450))
ellipse(screen, (0, 0, 0), (3, 490, 250, 450), 1)

ellipse(screen, color, (210, 600, 120, 40))
ellipse(screen, (0, 0, 0), (210, 600, 120, 40), 1)

ellipse(screen, color, (140, 820, 180, 130))
ellipse(screen, (0, 0, 0), (140, 820, 180, 130), 1)

ellipse(screen, color, (255, 935, 140, 45))
ellipse(screen, (0, 0, 0), (255, 935, 140, 45), 1)

ellipse(screen, (22, 80, 68), (475, 810, 300, 70))
ellipse(screen, (0, 0, 0), (475, 810, 300, 70), 1)

circle(screen, (255, 0, 0), (1170, 400), 50)
circle(screen, (0, 0, 0), (1170, 400), 25)

pygame.display.update()
clock = pygame.time.Clock()
finished = False

while not finished:
    clock.tick(FPS)
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            finished = True

pygame.quit()